### ISSUE TITLE
Provide example of BaseView usage

### ISSUE THREAD

**Issue by agmontpetit** [rrousselGit/provider-example#1]
I've found this example and it seems to me an enhancement of [this approach](https://github.com/FilledStacks/flutter-tutorials/blob/master/014-provider-v3-updates/2-final/lib/ui/views/base_widget.dart).

However, I'm having a hard time using `BaseView` and was wondering if you could provide an example of usage, since AFAIK it is not being used at the moment.

**Comment by rrousselGit** [comment]
this example is not official. It is a fork of Filled-stack example based on a discussion we had

I wouldn't recommend using it
